### ISSUE TITLE
Error when try to import api using apimcli tool in windows

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim-tooling#134]
**Description:**
We have an API Manager 2.6.0 which is running in the Linux machine. Then we had an apimcli tool which is used in the windows machine to export and then import the api. I have exported the api successfully. When I import the API I got the following error in the apim.

`[2019-11-01 17:05:03,257]  WARN - CompositeValve To enable SaaS mode for the webapp, /api-import-export-2.6.0-v10, configure the CarbonTomcatRealm in META-INF/context.xml.
[2019-11-01 17:05:03,286]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2019-11-01 17:05:03,286+0530]
[2019-11-01 17:05:03,289]  INFO - AuthenticatorUtil admin user authenticated successfully
[2019-11-01 17:05:03,315]  INFO - AuthenticatorUtil admin is authorized to import and export APIs
[2019-11-01 17:08:03,743]  INFO - InboundDBSyncRequestEvent Running DB sync task.
[2019-11-01 17:08:11,240] ERROR - APIService Error in reading API definition.
java.io.IOException: Cannot find API definition. api.json or api.yaml should present
	at org.wso2.carbon.apimgt.importexport.utils.APIImportUtil.importAPI(APIImportUtil.java:326)
	at org.wso2.carbon.apimgt.importexport.APIService.importAPI(APIService.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:603)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

I got the following error in the apimcli tool.
`[INFO]: Import URL: https://localhost:9443/api-import-export-2.6.0-v10/import-api?preserveProvider=false
Error importing API.
Status: 500 Internal Server Error
Response: Error occurred while adding the API. A duplicate API already exists for Rest-1.0.0
[INFO]: Deleting /var/folders/t5/wh2d7tyd18v4tswy0kc1byl80000gn/T/api-artifact280304798.zip
[INFO]: Deleting /var/folders/t5/wh2d7tyd18v4tswy0kc1byl80000gn/T/apim348006267/Rest-1.0.0
apimcli: Error importing API Reason: 500 Internal Server Error
Exit status 1`

**Affected Product Version:**
WSO2 API Manager Tooling 2.0.1

**Steps to reproduce:**
- Start wso2 apim 260 in a Linux operating system and create an API for the testing purpose.
-  Set up the apimcli tool for a Windows instance (need to deploy the relevant web app to the Linux instance's apim server)
- Export the created API using the apimcli tool installed in the windows OS (instance)
- Delete the relevant API from the apim server (using publisher)
- Try to import the exported API using the apimcli in windows OS

This issue occurs when we have an API Manager in the Linux/Mac environment and when we try to export and import the API from the windows environment.

**Comment by dinusha92** [comment]
Did you try the latest distribution for 2.6.0?

https://github.com/wso2/product-apim-tooling/releases/tag/v2.0.1

**Comment by Senthuran100** [comment]
We have tried with the latest distribution of API Manager 2.6.0 (timestamp:- 1572374428929).
