### ISSUE TITLE
Doesn't import SOAP API properly

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#253]
**Description:**
1. Import the API attached 
[stockSOAP-1.0.1.zip](https://github.com/wso2/product-apim-tooling/files/4416488/stockSOAP-1.0.1.zip)
2. Login to Publisher in API Manager -> click the imported API -> WSDL Definition
![image](https://user-images.githubusercontent.com/1591316/78163490-166dc400-7466-11ea-8c5e-a90b72ac9bbe.png)

3. Try to download the WSDL from Dev portal in the API overview section. It will be failed.
```
[2020-04-01 22:04:55,922] ERROR - GlobalThrowableMapper A defined exception has been captured and mapped to an HTTP response by the global exception mapper 
org.wso2.carbon.apimgt.api.APIManagementException: No WSDL found for the API: admin-stockSOAP-1.0.2
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getWSDL_aroundBody58(AbstractAPIManager.java:1119) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getWSDL(AbstractAPIManager.java:1087) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL_aroundBody234(APIConsumerImpl.java:5152) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getWSDL(APIConsumerImpl.java:5149) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApisApiServiceImpl.getWSDLOfAPI(ApisApiServiceImpl.java:845) ~[classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApisApi.getWSDLOfAPI(ApisApi.java:378) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
```

The issue is caused By: 
https://github.com/wso2/product-apim/issues/7862

**Comment by wasuradananjith** [comment]
I checked with different types of users, but both downloading/exporting and importing worked as expected.
