### ISSUE TITLE
Cannot create new versions of APIs with scopes

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#263]
**Description:**
Use the swagger [swagger.yaml.zip](https://github.com/wso2/product-apim-tooling/files/4427082/swagger.yaml.zip) and create a project
```
apictl init petstore --oas swagger.yaml --initial-state=PUBLISHED 
```
Import the project:
```
apictl import-api -f petstore/ --update -e dev
```

Now In api.yaml file, change the version as below:
```
id:
  providerName: admin
  apiName: Swagger Petstore New
  version: 4.0.0
description: 'This is a sample server Petstore server.  You can find out more about
  Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
  this sample, you can use the api key `special-key` to test the authorization filters.'
type: HTTP
context: /petstore/v1/4.0.0
```
Again import it to create a new version. 
It fails:
```
$ apictl import-api -f petstore/ --update -e dev
The specified API was not found.
Creating: Swagger Petstore New 3.0.0
Error importing API.
Status: 500 
Response: {"code":500,"message":"Internal server error","description":"Error while importing API","moreInfo":"","error":[]}
apictl: Error importing API Reason: 500 
Exit status 1

```

Server terminal:
```
[2020-04-03 17:38:51,303] ERROR - ImportApiServiceImpl Error while importing API
org.wso2.carbon.apimgt.impl.importexport.APIImportExportException: Error in adding API. Scope read is already assigned by another API.
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI_aroundBody6(APIImportUtil.java:407) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.APIImportUtil.importAPI(APIImportUtil.java:230) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.importAPIArchive_aroundBody6(APIImportExportManager.java:118) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.APIImportExportManager.importAPIArchive(APIImportExportManager.java:108) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.impl.ImportApiServiceImpl.importApiPost(ImportApiServiceImpl.java:101) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.admin.ImportApi.importApiPost(ImportApi.java:52) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor792.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
```

**Comment by malinthaprasan** [comment]
Mistake. Had used a wrong scope "read" assigned to a different API.
Closing,
