### ISSUE TITLE
Error Initializing API Project which has a "%" symbol in the Definition

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim-tooling#509]
**Description:**

When using [1] to initialize an API Project using apictl init command, the following error message was printed.
```
panic: parse "#/paths/~1stats~1id~1{plateform}~1{id}/get/responses/200/schema/properties/lifetimeStats/properties/win%": invalid URL escape "%"

goroutine 1 [running]:
github.com/go-openapi/jsonreference.MustCreateRef(0xc0000896c0, 0x68, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/naduni/go/pkg/mod/github.com/go-openapi/jsonreference@v0.19.3/reference.go:55 +0xbe
github.com/go-openapi/spec.MustCreateRef(...)
	/home/naduni/go/pkg/mod/github.com/go-openapi/spec@v0.19.4/ref.go:129
github.com/go-openapi/analysis.(*Spec).analyzeSchema(0xc0002b45b0, 0xc00011fd04, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:394 +0x1a7
github.com/go-openapi/analysis.(*Spec).analyzeSchema(0xc0002b45b0, 0xc0003f8480, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:414 +0x7e2
github.com/go-openapi/analysis.(*Spec).analyzeSchema(0xc0002b45b0, 0xec620d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:414 +0x7e2
github.com/go-openapi/analysis.(*Spec).analyzeOperation(0xc0002b45b0, 0xec4592, 0x3, 0xc000486f00, 0x1a, 0xc0001781c0)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:383 +0xe66
github.com/go-openapi/analysis.(*Spec).analyzeOperations(0xc0002b45b0, 0xc000486f00, 0x1a, 0xc00054eb20)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:269 +0xa2
github.com/go-openapi/analysis.(*Spec).initialize(0xc0002b45b0)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:215 +0x35d
github.com/go-openapi/analysis.New(0xc0000b6100, 0xc0000b7900)
	/home/naduni/go/pkg/mod/github.com/go-openapi/analysis@v0.19.5/analyzer.go:151 +0x5f
github.com/go-openapi/loads.Analyzed(0xc000172000, 0x38fe, 0x38fe, 0x0, 0x0, 0x0, 0x0, 0x40e668)
	/home/naduni/go/pkg/mod/github.com/go-openapi/loads@v0.19.4/spec.go:190 +0x23e
github.com/go-openapi/loads.Spec(0x7fff4ac39088, 0x7d, 0x1, 0x7fff4ac39088, 0x7d)
	/home/naduni/go/pkg/mod/github.com/go-openapi/loads@v0.19.4/spec.go:128 +0x12d
github.com/wso2/product-apim-tooling/import-export-cli/cmd.loadSwagger(0x7fff4ac39088, 0x7d, 0x0, 0x0, 0x2)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/init.go:103 +0xe4
github.com/wso2/product-apim-tooling/import-export-cli/cmd.executeInitCmd(0x1040720, 0xc00047fb30)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/init.go:160 +0x266
github.com/wso2/product-apim-tooling/import-export-cli/cmd.glob..func23(0x16e5160, 0xc00047fad0, 0x1, 0x3)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/init.go:321 +0x16f
github.com/spf13/cobra.(*Command).execute(0x16e5160, 0xc00047fa40, 0x3, 0x3, 0x16e5160, 0xc00047fa40)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x16e6a60, 0x443aba, 0x16872c0, 0xc000000180)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/wso2/product-apim-tooling/import-export-cli/cmd.Execute()
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/root.go:79 +0x31
main.main()
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/apictl.go:24 +0x20
```
There are % symbols in the definition. [2].
It is possible to import these APIs using the publisher UI and publish them to the devportal.

**Suggested Labels:**
Import-third-party-APIs

**Affected Product Version:**
apictl-3.2.0

**OS, DB, other environment details and versions:**
OS: Ubuntu 20.04.1 LTS (64-bit)

**Steps to reproduce:**
1. Use [1] as the --oas parameter value and initialize an API project using apictl. This would result in the error message.
![percentage_error](https://user-images.githubusercontent.com/30455603/96674872-4db2ac80-1387-11eb-8561-913d5c13bfd2.png)

[1] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/skynewz-api-fortnite.herokuapp.com/3.1.5/swagger.yaml
[2] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/skynewz-api-fortnite.herokuapp.com/3.1.5/swagger.yaml#L295

**Comment by npamudika** [comment]
YAML doesn't require quoting for most of the strings, but it needs to quote the special characters if they fall within a certain list of characters. You need to use quotes if your value includes any of the following special characters, (e.g. :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, ).

The definition you have used has special characters without the quotation marks and that is the reason behind the parsing failure you have noticed. Please use a valid definition file adhering to the standards.
