### ISSUE TITLE
NumberFormatException thrown for retryTimeOut and retryDelay after importing an API with a params file

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#665]
**Description:**
Exceptions come when importing an API with params that consists **retryTimeOut** and **retryDelay** under the endpoint configurations.

**Affected Product Version:**
APICTL 4.0.0-Alpha2

**Steps to reproduce:**
1. Add an environment as shown below.
```
apictl add env development --apim  https://localhost:9443 
```
2. Create an API Project the **apict init** command.
```
apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json
```
3. Open a text editor and create a params file with the below content. (Make sure to have **config** parameters such as **retryTimeOut** and **retryDelay** under the endpoints)
```
environments:
    - name: development
      configs:
          endpoints:
              production:
                  url: https://petstore.swagger.io/v2
                  config:
                      retryTimeOut: 10
                      retryDelay: 5
              sandbox:
                  url: https://sand.petstore.swagger.io/v2
```
4. Login to the env `development` using `apictl login development`
5. Import the API project with the params file using the below command.
```
apictl import api -f Petstore/ --params params_with_endpoint_configs.yaml -e development
```
6. Even though it states the API import is successful, check the server console and you can find the below error logs.
```
[2021-03-19 20:49:48,864] ERROR - EndpointDefinitionFactory The retries before suspend [for timeouts] should be specified as a valid number :                 10.0
                
java.lang.NumberFormatException: For input string: "10.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_251]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_251]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_251]
	at org.apache.synapse.config.xml.endpoints.EndpointDefinitionFactory.createDefinition(EndpointDefinitionFactory.java:223) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.HTTPEndpointFactory.createEndpointDefinition(HTTPEndpointFactory.java:56) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.HTTPEndpointFactory.createEndpoint(HTTPEndpointFactory.java:94) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.createEndpointWithName(EndpointFactory.java:143) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineEndpoint(SynapseXMLConfigurationFactory.java:284) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:183) [org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:95) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:84) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody20(InMemoryAPIDeployer.java:370) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:366) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:137) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[2021-03-19 20:49:48,875]  WARN - SynapseXMLConfigurationFactory Endpoint configuration: SwaggerPetstore--v1.0.5_APIproductionEndpoint cannot be built - Continue in fail-safe mode
org.apache.synapse.SynapseException: The retries before suspend [for timeouts] should be specified as a valid number :                 10.0
                
	at org.apache.synapse.config.xml.endpoints.EndpointDefinitionFactory.handleException(EndpointDefinitionFactory.java:378) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.EndpointDefinitionFactory.createDefinition(EndpointDefinitionFactory.java:225) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.HTTPEndpointFactory.createEndpointDefinition(HTTPEndpointFactory.java:56) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.HTTPEndpointFactory.createEndpoint(HTTPEndpointFactory.java:94) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.createEndpointWithName(EndpointFactory.java:143) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineEndpoint(SynapseXMLConfigurationFactory.java:284) [synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:183) [org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:95) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:84) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody20(InMemoryAPIDeployer.java:370) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:366) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:137) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NumberFormatException: For input string: "10.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_251]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_251]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_251]
	at org.apache.synapse.config.xml.endpoints.EndpointDefinitionFactory.createDefinition(EndpointDefinitionFactory.java:223) ~[synapse-core_2.1.7.wso2v208.jar:2.1.7-wso2v208]
	... 24 more
[2021-03-19 20:49:48,877] ERROR - EndpointAdmin Unable to create endpoint
[2021-03-19 20:49:48,879] ERROR - EndpointAdminServiceProxy Error adding endpoint file to the gateway
org.wso2.carbon.endpoint.EndpointAdminException: Unable to create endpoint
	at org.wso2.carbon.endpoint.service.EndpointAdmin.handleFault(EndpointAdmin.java:599) ~[org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:188) ~[org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:95) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:84) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody20(InMemoryAPIDeployer.java:370) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:366) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:137) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[2021-03-19 20:49:48,880] ERROR - InMemoryAPIDeployer Error deploying 1c628c0e-5dbc-4e4b-b78c-306e5083061e in Gateway
org.apache.axis2.AxisFault: Error while adding the endpoint fileUnable to create endpoint
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:65) ~[org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55) ~[org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696) ~[org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) ~[org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:95) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:84) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody20(InMemoryAPIDeployer.java:370) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:366) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:137) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:118) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:93) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:69) [org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.71.SNAPSHOT.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: org.wso2.carbon.endpoint.EndpointAdminException: Unable to create endpoint
	at org.wso2.carbon.endpoint.service.EndpointAdmin.handleFault(EndpointAdmin.java:599) ~[org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:188) ~[org.wso2.carbon.endpoint_4.7.84.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59) ~[org.wso2.carbon.apimgt.gateway_9.0.71.SNAPSHOT.jar:?]
	... 17 more
[2021-03-19 20:49:48,881] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 1c628c0e-5dbc-4e4b-b78c-306e5083061ein the Gateway
```

**Note:-**The above error states that the exception comes from **retryTimeOut: 10**. The configs was not processed after encountering the exception from **retryTimeOut**. But the same error comes for **retryDelay: 5** as well. To get that error remove **retryTimeOut: 10** from the params file and reimport the API.

**Comment by wasuradananjith** [comment]
APIM expecting these values to be strings. For example,
```
config:
    retryTimeOut: "10"
    retryDelay: "5"
```
Hence we need to update the docs with proper examples.
