### ISSUE TITLE
Importing APIs/API Products projects which contain certs with Windows carraige returns fails

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim-tooling#713]
**Description:**
Attempting to import APIs/API Products that contain certs that are generated on Windows(in either the project itself or the deployment directory) will fail due to the code relying on the constant string "-----BEGIN CERTIFICATE-----\n" as the delimiter when reading the certificate content as a string.

On Windows this will be "-----BEGIN CERTIFICATE-----\r\n" due to the carriage return. Therefore this causes the certificate string to not be read properly in this scenario. 

**OS, DB, other environment details and versions:**    
Windows

**Comment by uvindra** [comment]
[DeploymentArtifacts_R2QWV7NC6UCJZRPSAPI-1.0.0.zip](https://github.com/wso2/product-apim-tooling/files/6358939/DeploymentArtifacts_R2QWV7NC6UCJZRPSAPI-1.0.0.zip)

[R2QWV7NC6UCJZRPSAPI_1.0.0.zip](https://github.com/wso2/product-apim-tooling/files/6358942/R2QWV7NC6UCJZRPSAPI_1.0.0.zip)

**Comment by uvindra** [comment]
The issue can be reproduced by using the above attachments to import the API in APIM as follows,

```
apictl import api -f /<path-to-file>/R2QWV7NC6UCJZRPSAPI_1.0.0.zip -e production -k --verbose --params /<path-to-file>/DeploymentArtifacts_R2QWV7NC6UCJZRPSAPI-1.0.0
```

**Comment by uvindra** [comment]
The resulting stack trace in APIM is as follows,

```
TID: [-1234] [api/am/publisher] [2021-04-22 18:55:38,743] ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - An unknown exception has been captured by the global exception mapper. jav
a.lang.UnsupportedOperationException: JsonNull
        at com.google.gson.JsonElement.getAsString(JsonElement.java:192)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.updateAPIWithCertificate(ImportUtils.java:1605)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.addEndpointCertificates(ImportUtils.java:1529)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.importApi(ImportUtils.java:289)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.importAPI(ImportExportAPIServiceImpl.java:191)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.importAPI(ApisApiServiceImpl.java:3905)
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.importAPI(ApisApi.java:1192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

```

**Comment by 1akshitha** [comment]
Closing the issue as the Fix is merged to master
