### ISSUE TITLE
Deploy command doesn't handle the error properly when the environment is not configured

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-apim-tooling#756]
**Description:**
When executing the `apictl vcs deploy -e <env>` command, the bellow error returns when the environment is not configured in `api_params.yaml` file. Please refer to the below error.
```
rnavagamuwa@randikan UserAPI % apictl vcs deploy -e prod
Deploying Projects (1)...

APIs (1) ...
1: UserAPI: (UserAPI)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x18c9e48]

goroutine 1 [running]:
github.com/wso2/product-apim-tooling/import-export-cli/impl.injectParamsToAPI(0xc0000365a0, 0x46, 0xc00014ff80, 0x5c, 0x7ffeefbffa0d, 0x4, 0x1, 0x0, 0x0)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/impl/importAPI.go:647 +0x198
github.com/wso2/product-apim-tooling/import-export-cli/impl.ImportAPI(0xc00003c480, 0x24, 0xc0000af2f0, 0x26, 0x7ffeefbffa0d, 0x4, 0xc0000361e0, 0x4c, 0x1ac8a29, 0xf, ...)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/impl/importAPI.go:978 +0x1121
github.com/wso2/product-apim-tooling/import-export-cli/impl.ImportAPIToEnv(0xc00003c480, 0x24, 0x7ffeefbffa0d, 0x4, 0xc0000361e0, 0x4c, 0x1ac8a29, 0xf, 0x101, 0xb, ...)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/impl/importAPI.go:927 +0xf8
github.com/wso2/product-apim-tooling/import-export-cli/git.deployUpdatedProjects(0xc00003c480, 0x24, 0xc0004af6b0, 0x24, 0x7ffeefbffa0d, 0x4, 0x1, 0xc0003a8060, 0x18bd867, 0x19c8b80, ...)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/git/gitUtils.go:363 +0x103e
github.com/wso2/product-apim-tooling/import-export-cli/git.DeployChangedFiles(0xc00003c480, 0x24, 0x7ffeefbffa0d, 0x4, 0xc0003a18a0)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/git/gitUtils.go:476 +0xbb
github.com/wso2/product-apim-tooling/import-export-cli/cmd.glob..func39(0x22e2d40, 0xc00040ffa0, 0x0, 0x2)
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/vcsDeploy.go:65 +0x1ba
github.com/spf13/cobra.(*Command).execute(0x22e2d40, 0xc00040ff40, 0x2, 0x2, 0x22e2d40, 0xc00040ff40)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x22e1940, 0x104134a, 0x22822c0, 0xc00005a778)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/naduni/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/wso2/product-apim-tooling/import-export-cli/cmd.Execute()
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/cmd/root.go:79 +0x31
main.main()
	/home/naduni/Documents/Wso2/CLI/product-apim-tooling/import-export-cli/apictl.go:24 +0x20
```
Instead of showing the local paths of the initial project build machine, better if a proper meaningful error is returned.

**Affected Product Version:**
```
rnavagamuwa@randikan UserAPI % apictl version
Version: 3.2.1
Build Date: 2020-09-29 12:54:56 UTC
```

**OS, DB, other environment details and versions:**    
```
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

**Steps to reproduce:**
Try to deploy to an environment without defining that in the `api_params.yaml` file

**Comment by wasuradananjith** [comment]
What actually **apictl vcs deploy** does is executing the **apictl import** commands internally. So the above-stated issue is not limited to only the **apictl vsc deploy**. You will face the issue when running **apictl import-api** without the environment in the api_params.yaml file. So the easiest steps to reproduce this issue are as follows.

Prerequisites:
Make sure to delete the .wso2apictl and .wso2apictl.local directories in your home directory

Steps:
1. Create an API project using the **apictl init** command.
    ```
     apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json
   ```
2. Add your environment using the **apictl add-env** command
    ```
    apictl add-env production --apim  https://localhost:9443 
   ```
3. Import the API project to your environment and you will face the above-stated error in the issue.
   ```
   apictl import-api -f Petstore -e production -k
   ```

**Comment by wasuradananjith** [comment]
This issue does not exist in master or in APIM 4.0.0, because the params file are decoupled from the source repository from APICTL 4.0.0 onwards.
