### ISSUE TITLE
Issues in listing APIs isung combined modifiers

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim-tooling#760]
**Description:**

- **Command:**  `apictl list apis --environment dev --query provider:admin --insecure`
- **Response :** 

![Screenshot from 2021-07-01 21-13-22](https://user-images.githubusercontent.com/60866295/124152499-3947b780-dab1-11eb-859e-6c8458a02a14.png)

- **Command** : `apictl list apis --environment dev --query provider:admin name:PizzaShackAPI --insecure`
- **Response :**  No APIs are returned. 

But the PizzaShackAPI is available matching this query.

- **Command** : `apictl list apis --environment dev --query version:1.0.0  status:PUBLISHED --insecure`
- **Response :**  No APIs are returned. 

But the PizzaShackAPI is available matching this query.

This behavior is reproducible with API products too.

Stack trace in carbon logs:

```
[2021-07-01 21:21:22,589] ERROR - CarbonContextCreatorValve Could not handle request: /api/am/publisher/v1/apis
java.lang.NullPointerException: null
	at org.wso2.carbon.tomcat.ext.internal.Utils.getAppNameFromRequest(Utils.java:104) ~[org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.initCarbonContext(CarbonContextCreatorValve.java:80) ~[org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:56) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

### Affected versions

- APICTL 3.2.2 tool

### Steps to reproduce

- Create an environment and and Create an API in it.

**Comment by wasuradananjith** [comment]
This feature is working in apictl 3.2.1. This must have been broken due to a change in apictl 3.2.2.
![image](https://user-images.githubusercontent.com/25246848/124159896-48326800-dab9-11eb-8869-5d7da314757e.png)
