### ISSUE TITLE
Prerequisite before fixing https://github.com/wso2/product-apim-tooling/issues/784

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#785]
**Description:**
There is a prerequisite that should be fixed before fixing [1].

**Affected Product Version:**
APICTL 3.2.x
APIM 3.2.0

**Steps to reproduce:**
1. Create an API using the Publisher Portal
2. Set endpoint security for the above created API using the Publisher Portal. Make sure to give OAuth 2.0 configurations.

```
tokenUrl: http://localhost:3001/token
clientId: Poc7i6mTj0ac3LyTW0szFzdt1gwa
clientSecret: edDEOOjlY0kgClxVlntwWVFve64a
```

![image](https://user-images.githubusercontent.com/25246848/134315431-144a495f-c04b-4c25-ba70-94f4161233ba.png)

3. After saving the changes, export the API using apictl.

```
apictl export-api -e production -n TestAPI -v 1.0
```
Exported artifact: [TestAPI_1.0.zip](https://github.com/wso2/product-apim-tooling/files/7209323/TestAPI_1.0.zip)

4. Check the api.yaml file inside the exported artifact. The endpointConfig will have the clientSecret in an encrypted form as shown below.

endpointConfig: '{"endpoint_type":"http","sandbox_endpoints":{"url":"https:\/\/run.mocky.io\/v3\/5ad436b4-199a-4800-baf0-47abca7481fa"},"endpoint_security":{"sandbox":{"password":null,"tokenUrl":null,"clientId":null,"clientSecret":null,"customParameters":"{}","type":null,"grantType":null,"enabled":false,"username":null},"production":{"password":null,"tokenUrl":"http:\/\/localhost:3001\/token","clientId":"Poc7i6mTj0ac3LyTW0szFzdt1gwa","clientSecret":"eyJjIjoiYUI5VU5henZlYVZNdG45WmtUbjROMUZJRmN5N3RVTXk5UXd6VENjT0pqbk5pVHE5dGZXdjJUU3lTd3BnYlNESklnOThDRnhsODZrNzlTYjVJNkU3cDVGejZ5Y2tFcjJBdlFMam5aTThjYkEySUVkSVlaL1FBNXp2Q0ZVVFhxRlRVZ0oxeG9Qa1kwVXl0YUJtL2MrSk10cWZLU3o4NVJCTkhlT2M5aS9vSWNLTFJwallrdzNmZnBpZnVoRmtmVUZUZEFiaTEwdms5NW1VdWZ4WG1lMUVlVE9YbUZKZ0xIbUdQYUZGb2kycnpybk1HK3hUTktVMXJpaWp6VDVDamdhTFM3L2VOOGtPR2dCa1ZaSXNMZG9hOVE2OTBtT05qTmZXRmZtYkJQL1lrWU5CdmJOMUxFdWZaWWVCdENGdmFPTng4MVJZRFRaVUhiYnFxbzZrWjloaUJBXHUwMDNkXHUwMDNkIiwidCI6IlJTQS9FQ0IvT0FFUHdpdGhTSEExYW5kTUdGMVBhZGRpbmciLCJ0cCI6IjU3RkYzOEQ5NzY2NEM3OTJGRjg4MDExNzFGMDQxOTFERUQ4ODc3OEQiLCJ0cGQiOiJTSEEtMSJ9","customParameters":"{}","type":"OAUTH","grantType":"CLIENT_CREDENTIALS","enabled":true,"username":null}},"production_endpoints":{"url":"https:\/\/run.mocky.io\/v3\/5ad436b4-199a-4800-baf0-47abca7481fa"}}'

5. When you reimport this API, there won't be any problem and it will successfully get imported.
6. But, if we are fixing [1], this endpointConfig object will get updated according to what the user has provided in the params file. Here, the user will provide the clientSecret in a plain text form. (but not in an encrypted form). If we implemented [1], then the endpointConfig will have a value as below.

endpointConfig: '{"endpoint_type":"http","sandbox_endpoints":{"url":"https:\/\/run.mocky.io\/v3\/5ad436b4-199a-4800-baf0-47abca7481fa"},"endpoint_security":{"sandbox":{"password":null,"tokenUrl":null,"clientId":null,"clientSecret":null,"customParameters":"{}","type":null,"grantType":null,"enabled":false,"username":null},"production":{"password":null,"tokenUrl":"http:\/\/localhost:3001\/token","clientId":"Poc7i6mTj0ac3LyTW0szFzdt1gwa","clientSecret":"edDEOOjlY0kgClxVlntwWVFve64a","customParameters":"{}","type":"OAUTH","grantType":"CLIENT_CREDENTIALS","enabled":true,"username":null}},"production_endpoints":{"url":"https:\/\/run.mocky.io\/v3\/5ad436b4-199a-4800-baf0-47abca7481fa"}}'

Note that the clientSecret is having a plain text value here.

7. Now, if you import the API, it will get successfully imported. But, if you view (GET) the API using the Publisher Portal UI (or REST API), an error will be logged in the server as below.

```
[2021-09-22 14:48:15,112] ERROR - APIMappingUtil Error while decrypting client credentials for API: admin-TestAPI-1.0
org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:265) ~[org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:329) ~[org.wso2.carbon.core_4.6.0.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.utils.mappings.APIMappingUtil.fromAPItoDTO(APIMappingUtil.java:877) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getAPIByID(ApisApiServiceImpl.java:4275) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getLifecycleState(ApisApiServiceImpl.java:2278) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.getLifecycleState(ApisApiServiceImpl.java:2257) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisApiIdLifecycleStateGet(ApisApiServiceImpl.java:2246) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisApiIdLifecycleStateGet(ApisApi.java:503) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [tomcat-servlet-api_9.0.31.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) [org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:103) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: org.wso2.carbon.crypto.api.CryptoException: An error occurred while decrypting using the algorithm : 'RSA/ECB/OAEPwithSHA1andMGF1Padding'
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:148) ~[org.wso2.carbon.crypto.provider_1.1.2.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.2.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:259) ~[org.wso2.carbon.core_4.6.0.jar:?]
	... 59 more
Caused by: org.bouncycastle.jcajce.provider.util.BadBlockException: unable to decrypt block
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2168) ~[?:1.8.0_251]
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:137) ~[org.wso2.carbon.crypto.provider_1.1.2.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.2.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:259) ~[org.wso2.carbon.core_4.6.0.jar:?]
	... 59 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_251]
	at org.bouncycastle.crypto.encodings.OAEPEncoding.decodeBlock(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.crypto.encodings.OAEPEncoding.processBlock(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2168) ~[?:1.8.0_251]
	at org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider.decrypt(KeyStoreBasedInternalCryptoProvider.java:137) ~[org.wso2.carbon.crypto.provider_1.1.2.jar:?]
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132) ~[org.wso2.carbon.crypto.impl_1.1.2.jar:?]
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:259) ~[org.wso2.carbon.core_4.6.0.jar:?]
	... 59 more
```
8. Now, if you check the Endpoints tab there won't be anything displayed there.

![image](https://user-images.githubusercontent.com/25246848/134317482-f5aaa937-2953-4e17-aba4-e2511dfb5c03.png)

The reason for the error in 7 is, that when importing we have assumed that the clientSecret is already encrypted. That is because, when exporting, the apictl exports clientSecret in an encrypted form and when importing too our code expects that. So, in order to fix [1], we need to fix this behaviour first.

**Solution**
1. Decrypt the clientSecret to plain text while exporting first.
2. During the import, encrypt the clientSecret again.

But, this might break existing use cases if any.

**Related Issues:**
[1] https://github.com/wso2/product-apim-tooling/issues/784

**Comment by wasuradananjith** [comment]
We can use a parameter such as **isSecretEncrypted**. If the user is setting the security using the params file, we can set isSecretEncrypted: false inside the endpointConfig as shown below (this will be happening internally from the Go/apictl side).

"sandbox":{
         "password":"",
         "tokenUrl":"http:\/\/localhost:3001\/token",
         "clientId":"Poc7i6mTj0ac3LyTW0szFzdt1gwa",
         "clientSecret":"edDEOOjlY0kgClxVlntwWVFve64a",
         "customParameters":"{}",
         "type":"OAUTH",
         "grantType":"PASSWORD",
         "enabled":true,
         "uniqueIdentifier":null,
         "username":"admin",
         **"isEncrypted": false**
  },
      "production":{
         "password":null,
         "tokenUrl":"http:\/\/localhost:3001\/token",
         "clientId":"Poc7i6mTj0ac3LyTW0szFzdt1gwa",
         "clientSecret":"edDEOOjlY0kgClxVlntwWVFve64a",
         "customParameters":"{}",
         "type":"OAUTH",
         "grantType":"CLIENT_CREDENTIALS",
         "enabled":true,
         "uniqueIdentifier":null,
         "username":null,
         **"isEncrypted": false**
    }
   }

So, when importing, the APIM server (Java side) has to process the endpointConfig, check whether the "isSecretEncrypted" is set to false and if so, encrypt the clientSecret.

In all the other cases we may not need this parameter. When exporting an API, this parameter will not be there at all (this is similar to the current behaviour). Hence, when importing an already exported artifact, we can check whether the parameter is there or not. Since it is not there at all, we can directly skip the encryption process.

This fix should go to the server-side, hence we need to WUM/U2 for APIM 3.2.0 this prior to the fix for [1].

[1] https://github.com/wso2/product-apim-tooling/issues/784
